### ISSUE TITLE
This is tagged as Version 2.0.1. But still it is showing 2.0.0 in the Beta companion

### ISSUE THREAD

**Issue by arunabacies** [bitfocus/companion-module-betr-support#5]

**Comment by josephdadams** [comment]
Package.json still shows v2.0.0. Please update to the correct version number and tag a new release that matches this version number

**Comment by VishnuCR913** [comment]
Version updated to v2.0.1 in package.json

**Comment by josephdadams** [comment]
I made a new `v2.0.2` in package.json and tagged a new release since you had already made a `v2.0.1` tag that had the wrong number in it's package.json commit. This `v2.0.2` is now included.
